controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
refuge_home:
    path: /
    controller: App\Controller\RefugeController::index
